import os
import time

print ('J/')
time.sleep(0.5)
os.system('clear')
print ('JO|')
time.sleep(0.5)
os.system('clear')
print ('JON/')
time.sleep(0.5)
os.system('clear')
print ('JON|')
time.sleep(0.5)
os.system('clear')
print ('JONI/')
time.sleep(0.5)
os.system('clear')
print ('JONIBO')
time.sleep(0.5)
os.system('clear')
print ('JONIBO/')
time.sleep(0.5)
os.system('clear')
print ('JONIBO|')
time.sleep(0.5)
os.system('clear')
print ('JONIBOT/')
time.sleep(0.5)
os.system('clear')
print ('JONIBOT|')
time.sleep(0.5)
os.system('clear')
print ('JONIBOT /')
time.sleep(0.5)
os.system('clear')
print ('JONIBOT G|')
time.sleep(0.5)
os.system('clear')
print ('JONIBOTHA/')
time.sleep(0.5)
os.system('clear')
print ('JONIBOTHAND|')
time.sleep(0.5)
os.system('clear')
print ('JONIBOTHAND/')
time.sleep(0.5)
os.system('clear')
print ('JONIBOTHANDS|')
time.sleep(0.5)
os.system('clear')
print ('JONIBOTHANDS/')
time.sleep(0.5)
os.system('clear')
print ('JONIBOTHANDS|')
time.sleep(0.5)
os.system('clear')
print ('JONIBOTHANDSO/')
time.sleep(0.5)
os.system('clear')
print ('JONIBOTHANSO|')
time.sleep(0.5)
os.system('clear')
print ('JONIBOTHANDSO/')
time.sleep(0.5)
os.system('clear')
print ('JONIBOTHANDSOM|')
time.sleep(0.5)
os.system('clear')
print ('JONIBOTHANDSOME/')
time.sleep(0.5)
os.system('clear')
print ('JONIBOTHANDSOME')
time.sleep(0.5)
